const alldata = [
    {
        title:"Shri Garib Nath Mandir",
        descriptio:"Baba Garibnath Dham is continuously gaining fame as an awakened and divine shrine of Lord Shiva. The devotion of pilgrims who come from far and wide grows even deeper after having a glimpse of the deity. The unwavering faith of the people in Lord Mahadev is not without reason—Shiva belongs to everyone.",
        image:"https://images.news18.com/ibnkhabar/uploads/2023/07/3186421_HYP_0_FB_IMG_1688393244279.jpg?im=Resize,width=450,aspect=fit,type=normal",
        location:"Garib Asthan Rd, Mahammadpur Kazi, Musahri, Muzaffarpur, Bihar 842001",
        city:"Muzaffarpur",
        type:"Religious"
    },
    {
        title:"Sahu Pokhar",
        description:"Sahu Pokhar has a history of over 250 years. It was built by the Sahu family, with its excavation done in 1754 by Shiv Sahai Prasad Sahu, son of landlord Bhawani Prasad Sahu. He also constructed the Shri Ram-Janaki Temple nearby. The history of the pond and temple is mentioned in the travel accounts of foreign scholar Dr. Spooner, who visited in 1917 and studied the temple's architecture during his tour of the Vajji-Vaishali region.",
        image:"https://assets.telegraphindia.com/telegraph/pond1.jpg",
        location:"Sahu Pokhar Purani Bazar,",
        city:"Muzaffarpur",
        type:"Religious",
    },
    
    {
        title:"Devi Mandir",
        description:"The famous Raj Rajeshwari Devi Temple, located in Umashankar Prasad Lane of the city, is considered one of the major Shakti Peeths of North Bihar. Devotees visit the temple throughout the year. It is said that hardly any shopkeeper in the city opens their store without first seeking the blessings of the goddess. It is believed that the presiding deity, Mata Shodashi, fulfills the wishes of every devotee. During Navratri, the temple witnesses a massive crowd of lakhs of people. Grand aartis are performed in the morning and evening during Navratri, attracting a large number of devotees. The temple premises become so crowded that there’s barely any space to step. Each year, the number of devotees continues to grow",
        image:"https://www.seawatersports.com/images/places/devi-mandir.png",
        location:"Mahammadpur Kazi, Mithanpura, Ramna-842002",
        city:"Muzaffarpur",
        type:"Religious",
    },
    {
        title:"Maa Baglamukhi Pitambari",
        description:"The renowned Maa Baglamukhi Peetambari Siddhapeeth, located on Kacchi Sarai Road in Muzaffarpur city, is famous for Tantric worship and is considered a major center for attaining Tantric powers during the special Nisha Puja held on the night of Saptami in Navratri.",
        image:"https://lh3.googleusercontent.com/p/AF1QipNM00evxx-cjrR2SdxfqH1LqGB-tWINybXuMZX7=w243-h406-n-k-no-nu",
        location:"Hathi Chowk, near Amar Cinema Road, Muzaffarpur Court.",
        city:"Muzaffarpur",
        type:"Religious"
    },
    {
        title:"Chhinmastika Mandir",
        description:"People say the temple has many unique features. Although the goddess is in her left-oriented (Vam) form and is associated with sacrifice, she is worshipped here in a pure Vaishnav (non-violent) tradition. Devotees and spiritual practitioners come from far and wide to perform sadhana (spiritual practice) and attain tantric powers. The Nisha Puja performed on every Amavasya (new moon night) holds special significance here. It is believed that Maa Chhinnamastika is connected to the origin point of creation. She is one of the most important goddesses among the ten Mahavidyas. According to scriptures, during the creation of the universe, the goddess beheaded herself and offered her blood to two yoginis to save the world from destruction. Great sages like Maharishi Yamadagni, Shukracharya, and Parashurama were among her chief devotees.",
        image:"https://www.bhaktvatsal.com/public/uploads/878e1079aa223288e5cb4d93cdb7ad43.webp",
        location:"NH-28 Kanti Muzaffarpur",
        city:"Muzaffarpur",
        type:"Religious",
    },
    {
        title:"Mata Kali Vaishno Devi Darbar",
        description:"While the famous Vaishno Devi temple is located in Katra, Jammu & Kashmir, Muzaffarpur also has a temple dedicated to Mata Vaishno Devi. This temple stands on 400 pillars. Resembling a white cave, the tall structure requires devotees to climb a steep path to reach the sanctum sanctorum of the goddess.",
        image:"https://content.jdmagicbox.com/comp/muzaffarpur/k1/9999px621.x621.220318221946.r3k1/catalogue/maa-kali-vaishno-mandir-kalyani-muzaffarpur-temples-d6LJ292fa7.jpg",
        location:"Punjabi Colony, Gannipur Road, Naya Tola",
        city:"Muzaffarpur",
        type:"Religious",
    },
    {
        title:"L.N. Mishra College",
        description:"NA",
        image:"NA",
        location:"NA",
        city:"Muzaffarpur",
        type:"",
    },
    {
        title:"L.N. Mishra College",
        description:"NA",
        image:"NA",
        location:"NA",
        city:"Muzaffarpur",
        type:"",
    },
    {
        title:"L.N. Mishra College",
        description:"NA",
        image:"NA",
        location:"NA",
        city:"Muzaffarpur",
        type:"",
    },
    {
        title:"L.N. Mishra College",
        description:"NA",
        image:"NA",
        location:"NA",
        city:"Muzaffarpur",
        type:"",
    },
    {
        title:"L.N. Mishra College",
        description:"NA",
        image:"NA",
        location:"NA",
        city:"Muzaffarpur",
        type:"",
    },
    {
        title:"L.N. Mishra College",
        description:"NA",
        image:"NA",
        location:"NA",
        city:"Muzaffarpur",
        type:"",
    },
    {
        title:"L.N. Mishra College",
        description:"NA",
        image:"NA",
        location:"NA",
        city:"Muzaffarpur",
        type:"",
    },
    {
        title:"L.N. Mishra College",
        description:"NA",
        image:"NA",
        location:"NA",
        city:"Muzaffarpur",
        type:"",
    },
    {
        title:"Muzaffarpur Park",
        description:"NA",
        image:"NA",
        location:"NA",
        city:"Muzaffarpur",
        type:"Park",
    },
    {
        title:"Jubba Sahni Park",
        description:"NA",
        image:"NA",
        location:"NA",
        city:"Muzaffarpur",
        type:"Park",
    },
    {
        title:"City Park",
        description:"NA",
        image:"NA",
        location:"NA",
        city:"Muzaffarpur",
        type:"Park",
    },
    {
        title:"Mahatma Gandhi Park",
        description:"NA",
        image:"NA",
        location:"NA",
        city:"Muzaffarpur",
        type:"Park",
    },
    {
        title:"Rajendra Park",
        description:"NA",
        image:"NA",
        location:"NA",
        city:"Muzaffarpur",
        type:"Park",
    },
    {
        title:"Sahara Bharat Mata Park",
        description:"NA",
        image:"NA",
        location:"NA",
        city:"Muzaffarpur",
        type:"Park",
    },
    {
        title:"Amrit Mahotsav Park",
        description:"NA",
        image:"NA",
        location:"NA",
        city:"Muzaffarpur",
        type:"Park",
    },
    {
        title:"Bharat Mata Naman Sthal",
        description:"NA",
        image:"NA",
        location:"NA",
        city:"Muzaffarpur",
        type:"Park",
    },
    {
        title:"University Park",
        description:"NA",
        image:"NA",
        location:"NA",
        city:"Muzaffarpur",
        type:"Park",
    },
    {
        title:"AMBEDKAR PARK",
        description:"NA",
        image:"NA",
        location:"NA",
        city:"Muzaffarpur",
        type:"Park",
    },
    {
        title:"The Grand Mall",
        description:"NA",
        image:"NA",
        location:"NA",
        city:"Muzaffarpur",
        type:"Mall",
    },
    {
        title:"P&M Mall",
        description:"NA",
        image:"NA",
        location:"NA",
        city:"Muzaffarpur",
        type:"Mall",
    },
    {
        title:"Icon Plaza",
        description:"NA",
        image:"NA",
        location:"NA",
        city:"Muzaffarpur",
        type:"Mall",
    },
    {
        title:"Gayatri Mall",
        description:"NA",
        image:"NA",
        location:"NA",
        city:"Muzaffarpur",
        type:"Mall",
    },
    {
        title:"Citykart ",
        description:"NA",
        image:"NA",
        location:"NA",
        city:"Muzaffarpur",
        type:"Mall",
    },
    {
        title:"Vishal Mega Mart",
        description:"NA",
        image:"NA",
        location:"NA",
        city:"Muzaffarpur",
        type:"Mall",
    },
    {
        title:"V Mart",
        description:"NA",
        image:"NA",
        location:"NA",
        city:"Muzaffarpur",
        type:"Mall",
    },
    {
        title:"Reliance SMART Bazaar",
        description:"NA",
        image:"NA",
        location:"NA",
        city:"Muzaffarpur",
        type:"Mall",
    },
    {
        title:"Khadi Mall",
        description:"NA",
        image:"NA",
        location:"NA",
        city:"Muzaffarpur",
        type:"Mall",
    },
    {
        title:"DCC Mall ",
        description:"NA",
        image:"NA",
        location:"NA",
        city:"Muzaffarpur",
        type:"Mall",
    },
    {
        title:"L.N. Mishra College",
        description:"NA",
        image:"NA",
        location:"NA",
        city:"Muzaffarpur",
        type:"",
    },
    {
        title:"L.N. Mishra College",
        description:"NA",
        image:"NA",
        location:"NA",
        city:"Muzaffarpur",
        type:"",
    },
    {
        title:"L.N. Mishra College",
        description:"NA",
        image:"NA",
        location:"NA",
        city:"Muzaffarpur",
        type:"",
    },
    {
        title:"L.N. Mishra College",
        description:"NA",
        image:"NA",
        location:"NA",
        city:"Muzaffarpur",
        type:"",
    },
    {
        title:"L.N. Mishra College",
        description:"NA",
        image:"NA",
        location:"NA",
        city:"Muzaffarpur",
        type:"",
    },
    {
        title:"L.N. Mishra College",
        description:"NA",
        image:"NA",
        location:"NA",
        city:"Muzaffarpur",
        type:"",
    },
    {
        title:"L.N. Mishra College",
        description:"NA",
        image:"NA",
        location:"NA",
        city:"Muzaffarpur",
        type:"",
    },
    {
        title:"L.N. Mishra College",
        description:"NA",
        image:"NA",
        location:"NA",
        city:"Muzaffarpur",
        type:"",
    },
    {
        title:"L.N. Mishra College",
        description:"NA",
        image:"NA",
        location:"NA",
        city:"Muzaffarpur",
        type:"",
    },
    {
        title:"L.N. Mishra College",
        description:"NA",
        image:"NA",
        location:"NA",
        city:"Muzaffarpur",
        type:"",
    },
    {
        title:"L.N. Mishra College",
        description:"NA",
        image:"NA",
        location:"NA",
        city:"Muzaffarpur",
        type:"",
    },
    {
        title:"L.N. Mishra College",
        description:"NA",
        image:"NA",
        location:"NA",
        city:"Muzaffarpur",
        type:"",
    },
    {
        title:"L.N. Mishra College",
        description:"NA",
        image:"NA",
        location:"NA",
        city:"Muzaffarpur",
        type:"",
    },
    {
        title:"L.N. Mishra College",
        description:"NA",
        image:"NA",
        location:"NA",
        city:"Muzaffarpur",
        type:"",
    },
    {
        title:"L.N. Mishra College",
        description:"NA",
        image:"NA",
        location:"NA",
        city:"Muzaffarpur",
        type:"",
    },
    {
        title:"L.N. Mishra College",
        description:"NA",
        image:"NA",
        location:"NA",
        city:"Muzaffarpur",
        type:"",
    },
    {
        title:"L.N. Mishra College",
        description:"NA",
        image:"NA",
        location:"NA",
        city:"Muzaffarpur",
        type:"",
    },
    {
        title:"L.N. Mishra College",
        description:"NA",
        image:"NA",
        location:"NA",
        city:"Muzaffarpur",
        type:"",
    },
    {
        title:"L.N. Mishra College",
        description:"NA",
        image:"NA",
        location:"NA",
        city:"Muzaffarpur",
        type:"",
    },
    {
        title:"L.N. Mishra College",
        description:"NA",
        image:"NA",
        location:"NA",
        city:"Muzaffarpur",
        type:"",
    },
    {
        title:"L.N. Mishra College",
        description:"NA",
        image:"NA",
        location:"NA",
        city:"Muzaffarpur",
        type:"",
    },
    {
        title:"L.N. Mishra College",
        description:"NA",
        image:"NA",
        location:"NA",
        city:"Muzaffarpur",
        type:"",
    },
    {
        title:"L.N. Mishra College",
        description:"NA",
        image:"NA",
        location:"NA",
        city:"Muzaffarpur",
        type:"",
    },
    {
        title:"L.N. Mishra College",
        description:"NA",
        image:"NA",
        location:"NA",
        city:"Muzaffarpur",
        type:"",
    },
    {
        title:"L.N. Mishra College",
        description:"NA",
        image:"NA",
        location:"NA",
        city:"Muzaffarpur",
        type:"",
    },
    {
        title:"L.N. Mishra College",
        description:"NA",
        image:"NA",
        location:"NA",
        city:"Muzaffarpur",
        type:"",
    },
    {
        title:"L.N. Mishra College",
        description:"NA",
        image:"NA",
        location:"NA",
        city:"Muzaffarpur",
        type:"",
    },
    {
        title:"L.N. Mishra College",
        description:"NA",
        image:"NA",
        location:"NA",
        city:"Muzaffarpur",
        type:"",
    },
    {
        title:"L.N. Mishra College",
        description:"NA",
        image:"NA",
        location:"NA",
        city:"Muzaffarpur",
        type:"",
    },
    {
        title:"L.N. Mishra College",
        description:"NA",
        image:"NA",
        location:"NA",
        city:"Muzaffarpur",
        type:"",
    },
    {
        title:"L.N. Mishra College",
        description:"NA",
        image:"NA",
        location:"NA",
        city:"Muzaffarpur",
        type:"",
    },
    {
        title:"L.N. Mishra College",
        description:"NA",
        image:"NA",
        location:"NA",
        city:"Muzaffarpur",
        type:"",
    },
    {
        title:"L.N. Mishra College",
        description:"NA",
        image:"NA",
        location:"NA",
        city:"Muzaffarpur",
        type:"",
    },
    {
        title:"L.N. Mishra College",
        description:"NA",
        image:"NA",
        location:"NA",
        city:"Muzaffarpur",
        type:"",
    },
    {
        title:"L.N. Mishra College",
        description:"NA",
        image:"NA",
        location:"NA",
        city:"Muzaffarpur",
        type:"",
    },
    {
        title:"L.N. Mishra College",
        description:"NA",
        image:"NA",
        location:"NA",
        city:"Muzaffarpur",
        type:"",
    },
    
];
module.exports = {data: alldata};