const alldata = [
    {
        title:"Shri Garib Nath Mandir",
        descriptio:"Baba Garibnath Dham is continuously gaining fame as an awakened and divine shrine of Lord Shiva. The devotion of pilgrims who come from far and wide grows even deeper after having a glimpse of the deity. The unwavering faith of the people in Lord Mahadev is not without reason—Shiva belongs to everyone.",
        image:"https://images.news18.com/ibnkhabar/uploads/2023/07/3186421_HYP_0_FB_IMG_1688393244279.jpg?im=Resize,width=450,aspect=fit,type=normal",
        location:"Garib Asthan Rd, Mahammadpur Kazi, Musahri, Muzaffarpur, Bihar 842001",
        city:"Muzaffarpur",
        type:"Religious"
    },
    {
        title:"Sahu Pokhar",
        description:"Sahu Pokhar has a history of over 250 years. It was built by the Sahu family, with its excavation done in 1754 by Shiv Sahai Prasad Sahu, son of landlord Bhawani Prasad Sahu. He also constructed the Shri Ram-Janaki Temple nearby. The history of the pond and temple is mentioned in the travel accounts of foreign scholar Dr. Spooner, who visited in 1917 and studied the temple's architecture during his tour of the Vajji-Vaishali region.",
        image:"https://assets.telegraphindia.com/telegraph/pond1.jpg",
        location:"Sahu Pokhar Purani Bazar,",
        city:"Muzaffarpur",
        type:"Religious",
    },
    
    {
        title:"Devi Mandir",
        description:"The famous Raj Rajeshwari Devi Temple, located in Umashankar Prasad Lane of the city, is considered one of the major Shakti Peeths of North Bihar. Devotees visit the temple throughout the year. It is said that hardly any shopkeeper in the city opens their store without first seeking the blessings of the goddess. It is believed that the presiding deity, Mata Shodashi, fulfills the wishes of every devotee. During Navratri, the temple witnesses a massive crowd of lakhs of people. Grand aartis are performed in the morning and evening during Navratri, attracting a large number of devotees. The temple premises become so crowded that there’s barely any space to step. Each year, the number of devotees continues to grow",
        image:"https://www.seawatersports.com/images/places/devi-mandir.png",
        location:"Mahammadpur Kazi, Mithanpura, Ramna-842002",
        city:"Muzaffarpur",
        type:"Religious",
    },
    {
        title:"Maa Baglamukhi Pitambari",
        description:"The renowned Maa Baglamukhi Peetambari Siddhapeeth, located on Kacchi Sarai Road in Muzaffarpur city, is famous for Tantric worship and is considered a major center for attaining Tantric powers during the special Nisha Puja held on the night of Saptami in Navratri.",
        image:"https://content.jdmagicbox.com/comp/muzaffarpur/n3/9999px621.x621.180308143318.t1n3/catalogue/bangla-mukhi-mandir-muzaffarpur-temples-1frb7ehjlk.jpg?clr=",
        location:"Hathi Chowk, near Amar Cinema Road, Muzaffarpur Court.",
        city:"Muzaffarpur",
        type:"Religious"
    },
    {
        title:"Chhinmastika Mandir",
        description:"People say the temple has many unique features. Although the goddess is in her left-oriented (Vam) form and is associated with sacrifice, she is worshipped here in a pure Vaishnav (non-violent) tradition. Devotees and spiritual practitioners come from far and wide to perform sadhana (spiritual practice) and attain tantric powers. The Nisha Puja performed on every Amavasya (new moon night) holds special significance here. It is believed that Maa Chhinnamastika is connected to the origin point of creation. She is one of the most important goddesses among the ten Mahavidyas. According to scriptures, during the creation of the universe, the goddess beheaded herself and offered her blood to two yoginis to save the world from destruction. Great sages like Maharishi Yamadagni, Shukracharya, and Parashurama were among her chief devotees.",
        image:"https://www.bhaktvatsal.com/public/uploads/878e1079aa223288e5cb4d93cdb7ad43.webp",
        location:"NH-28 Kanti Muzaffarpur",
        city:"Muzaffarpur",
        type:"Religious",
    },
    {
        title:"Mata Kali Vaishno Devi Darbar",
        description:"While the famous Vaishno Devi temple is located in Katra, Jammu & Kashmir, Muzaffarpur also has a temple dedicated to Mata Vaishno Devi. This temple stands on 400 pillars. Resembling a white cave, the tall structure requires devotees to climb a steep path to reach the sanctum sanctorum of the goddess.",
        image:"https://content.jdmagicbox.com/comp/muzaffarpur/k1/9999px621.x621.220318221946.r3k1/catalogue/maa-kali-vaishno-mandir-kalyani-muzaffarpur-temples-d6LJ292fa7.jpg",
        location:"Punjabi Colony, Gannipur Road, Naya Tola",
        city:"Muzaffarpur",
        type:"Religious",
    },
    {
        title:"Bhairav Sthan Mandir",
        description:"Bhairav Sthan Mandir is a famous temple in Muzaffarpur, Bihar, dedicated to Lord Bhairav. It is located in the Bhairav Sthan locality of the city. The temple is known for its unique architecture and attracts a large number of devotees, especially during festivals and auspicious occasions.",
        image:"https://content3.jdmagicbox.com/comp/muzaffarpur/x4/9999px621.x621.180222213938.h6x4/catalogue/bhairav-sthan-mandir-muzaffarpur-temples-va5c36lpf0.jpg",
        location:"Ramnagra Rod Aurai, Aurai, Muzaffarpur - 843312.",
        city:"Muzaffarpur",
        type:"Religious",
    },
    {
        title:"Santoshi Mata Mandir",
        description:"Santoshi Mata Mandir is a popular temple in Muzaffarpur, Bihar, dedicated to Goddess Santoshi Mata. The temple is known for its serene atmosphere and attracts devotees seeking blessings and fulfillment of their wishes. It is especially crowded on Fridays, which is considered an auspicious day for worshipping the goddess.",
        image:"https://content.jdmagicbox.com/comp/muzaffarpur/i9/9999px621.x621.200628233400.w8i9/catalogue/santoshi-mata-mandir-motijheel-muzaffarpur-temples-3CsIf85Luw.jpg",
        location:" Motijheel Road, Motijheel, Muzaffarpur - 842001",
        city:"Muzaffarpur",
        type:"Religious",
    },
    {
        title:"Gayatri Mandir",
        description:"Gayatri Mandir is a revered temple in Muzaffarpur, Bihar, dedicated to Goddess Gayatri. The temple is known for its spiritual ambiance and attracts devotees seeking blessings and guidance from the goddess. It is a popular place of worship, especially during festivals and auspicious occasions.",
        image:"https://www.tripnight.com/public/thumbs/monuments/1151/cgjaszTJQk7h_468_738.jpg",
        location:"Ahiyapur, Muzaffarpur - 843125",
        city:"Muzaffarpur",
        type:"Religious",
    },
    {
        title:"Durgasthan Mandir",
        description:"Durgasthan Mandir is a prominent temple in Muzaffarpur, Bihar, dedicated to Goddess Durga. The temple is known for its vibrant atmosphere and attracts a large number of devotees, especially during the Navratri festival. It is a significant place of worship for the local community.",
        image:"https://content.jdmagicbox.com/comp/muzaffarpur/i6/9999px621.x621.190331181717.s3i6/catalogue/durgasthan-mandir-muzaffarpur-temples-9dw5ct0kcf.jpg",
        location:"Musahri, Muzaffarpur - 842001",
        city:"Muzaffarpur",
        type:"Religious",
    },
    {
        title:"Ram Janki Mandir",
        description:"Ram Janki Mandir is a well-known temple in Muzaffarpur, Bihar, dedicated to Lord Rama and Goddess Sita. The temple is famous for its beautiful architecture and serene environment. It attracts devotees from all over the region, especially during festivals like Ram Navami.",
        image:"https://files.yappe.in/place/full/ram-janki-mandir-5333793.webp",
        location:"Mahammadpur Kazi, Chandwara, Muzaffarpur - 842001",
        city:"Muzaffarpur",
        type:"Religious",
    },
    {
        title:"Shri Shyam Mandir",
        description:"Shri Shyam Mandir is a popular temple in Muzaffarpur, Bihar, dedicated to Lord Shyam (Lord Krishna). The temple is known for its vibrant atmosphere and attracts a large number of devotees, especially during festivals and special occasions. It is a significant place of worship for the local community.",
        image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTU81J_cDjW3MVv9e_mNtb8jwJEqOMjQCeFsQ&s",
        location:"Sutapatti, Muzaffarpur - 842001",
        city:"Muzaffarpur",
        type:"Religious",
    },
    {
        title:"Chamunda Mandir",
        description:"Chamunda Mandir in Katra, Muzaffarpur, is a revered Hindu temple dedicated to Goddess Chamunda, believed to have manifested in a pindi (stone) form. According to legend, it was at this site that Goddess Durga defeated the demon brothers Chanda and Munda, and the temple has been a center of worship since the Ramayana era.",
        image:"https://www.jagranimages.com/images/newimg/25072022/25_07_2022-chamunda_sthan_mandir_katra_muzaffarpur_22922365.webp",
        location:"Majhauli Road, Katra, Muzaffarpur - 843321",
        city:"Muzaffarpur",
        type:"Religious",
    },
    {
        title:"Mahavir Peeth Hindu Temple",
        description:"Mahavir Peeth Hindu Temple in Muzaffarpur is a prominent religious site dedicated to Lord Hanuman, attracting numerous devotees daily for worship and spiritual solace. The temple is renowned for its serene ambiance and is especially vibrant during festivals like Ram Navami, drawing large crowds of devotees.",
        image:"https://content.jdmagicbox.com/comp/muzaffarpur/d7/9999px621.x621.180301201621.t1d7/catalogue/mahavir-peeth-hindu-temple-chandwara-muzaffarpur-temples-xf2bjx7cd1.jpg",
        location:"Chandwara, Muzaffarpur - 842001.",
        city:"Muzaffarpur",
        type:"Religious",
    },
    {
        title:"Nehru Park",
        description:"Nehru Park in Muzaffarpur, also known as Muzaffarpur Park, is a popular green space ideal for morning walks, family outings, and relaxation. It features landscaped gardens, walking paths, and play areas, making it a favored spot among locals.",
        image:"https://thumbs.dreamstime.com/b/nehru-park-new-delhi-looking-beautiful-colorful-spring-flowers-blooming-india-175620754.jpg",
        location:"Company Bagh Road, Sutapatti, Pokhraira, Muzaffarpur, Bihar 842001",
        city:"Muzaffarpur",
        type:"Park",
    },
    {
        title:"Jubba Sahni Park",
        description:"The park is situated in a commercial area and is a good place for picnics, family get-togethers, and morning walks. The park has attractions for children, a quiet space for elders, a fountain, and a well-manicured garden. ",
        image:"https://travelsetu.com/apps/uploads/new_destinations_photos/destination/2024/01/06/bd3469d6cde3dd1157f540c570b33826_1000x1000.jpg",
        location:"Sutapatti, Pokhraira, Muzaffarpur - 842001",
        city:"Muzaffarpur",
        type:"Park",
    },
    {
        title:"City Park",
        description:"City Park in Muzaffarpur is a well-maintained park offering a variety of recreational activities and amenities. It's known for its lush greenery, vibrant flowers, and a playground area suitable for children of all ages. The park also has walking areas, gym equipment, and a designated area for birds like ducks.",
        image:"https://images.openai.com/thumbnail-content/lh3/gps-cs-s/AC9h4nr8VFl-LcuFc3ThytIBqpIXTpE8i02CBC0VbBqgadlJ0TLXyhCQClVNu5ABRnUWiY56AwllC3NVhX20pV6ZSYFAKmZPtSthjWxkfRgTQiSIRXZcZsCi2VKTlzfCwpfvj6mvFlo6",
        location:"adar hospital road Companybagh, 49FJ VXV, near S. P. Office, near Ssp, Sutapatti, Pokhraira, Muzaffarpur, Bihar 842001",
        city:"Muzaffarpur",
        type:"Park",
    },
    {
        title:"Mahatma Gandhi Park",
        description:"Mahatma Gandhi Park in Bangalore is a popular park featuring statues of Mahatma Gandhi in different poses, well-maintained trees, and a good space for relaxation.",
        image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSCq7dWvQkQEog0LZPzy0QQ21cMLHX5XoYgSQ&s",
        location:"497J+94W, B.R.Ambedkar Bihar University, Muzaffarpur, Bihar 842001",
        city:"Muzaffarpur",
        type:"Park",
    },
    {
        title:"Rajendra Park",
        description:"It's a well-known park in the area, frequently visited by locals.",
        image:"https://content.jdmagicbox.com/comp/chandigarh/j9/0172px172.x172.170315163856.p4j9/catalogue/rajendra-park-vigyanpath-chandigarh-tourist-attraction-2lfb4wn.jpg",
        location:"Rajendra Park is a park located in Muzaffarpur, Bihar, near the Muzaffarpur railway station.",
        city:"Muzaffarpur",
        type:"Park",
    },
    {
        title:"Sahara Bharat Mata Park",
        description:"Sahara Bharat Mata Park is a park located in Muzaffarpur, Bihar. The average rating of this place is 4.10 out of 5 stars based on 42 reviews. The street address of this place is 49FJ+P3M, Sutapatti, Pokhraira, Muzaffarpur, Bihar 842001, India. It is about 1.02 kilometers away from the Muzaffarpur railway station.",
        image:"https://files.yappe.in/place/full/sahara-bharat-mata-park-3581788.webp",
        location:"49FJ+P3M, Sutapatti, Pokhraira, Muzaffarpur, Bihar 842001",
        type:"Park",
    },
    {
        title:"Amrit Mahotsav Park",
        description:"The Amrit Mahotsav Park in Muzaffarpur is a recreational space with various features, including a museum, a children's park, and a musical fountain.",
        image:"https://images.bhaskarassets.com/thumb/1200x900/web2images/521/2023/12/29/28muzaffarpur-city-pg-2-0_c732131d-4652-402c-aad0-5f8111c7994b-large.jpg",
        location:"Amrit Mahotsav Park in Pokhraira,Muzaffarpur ",
        city:"Muzaffarpur",
        type:"Park",
    },
    {
        title:"Bharat Mata Naman Sthal",
        description:"Bharat Maa Naman Sthal Park offers a wealth of natural beauty and recreational opportunities.",
        image:"https://ind.5bestincity.com/profileimages/india/bharat-mata-naman-sthal-public-parks-muzaffarpur-bihar/29702-cde86-1.jpg",
        location:"49FJ+P4C, Juran Chhapra Main Rd, Sutapatti, Pokhraira, Muzaffarpur, Bihar 842001",
        city:"Muzaffarpur",
        type:"Park",
    },
    {
        title:"University Park",
        description:" University Park in Muzaffarpur serves as a valuable green space offering a peaceful escape for the community.",
        image:"https://content3.jdmagicbox.com/v2/comp/muzaffarpur/b5/9999px621.x621.101229144145.c8b5/catalogue/rameshwar-singh-college-muzaffarpur-ho-muzaffarpur-colleges-es0gbuvopq.jpg",
        location:"497jc7j Mahatma Gandhi Koop Udyaan, B.R.Ambedkar Bihar University, Muzaffarpur - 842001. ",
        city:"Muzaffarpur",
        type:"Park",
    },
    {
        title:"AMBEDKAR PARK",
        description:"Ambedkar Park in Muzaffarpur is a well-maintained green space offering a variety of amenities, including play equipment for children and walking lanes",
        image:"https://content.jdmagicbox.com/comp/muzaffarpur/l6/9999px621.x621.220414203822.y4l6/catalogue/afsana-ejaj-garden-patiyasha-ramna-muzaffarpur-parks-mlzai00lgp.jpg",
        location:"49FJ+C6G, Sutapatti, Pokhraira, Muzaffarpur, Bihar 842001",
        city:"Muzaffarpur",
        type:"Park",
    },
    {
        title:"The Grand Mall",
        description:"The Grand Mall in Muzaffarpur is a prominent shopping and entertainment destination situated in Mithanpura. It offers a variety of retail outlets featuring fashion, accessories, electronics, and more.The mall also houses a Cinepolis multiplex cinema for movie enthusiasts and a food court with diverse dining options.",
        image:"https://www.walk2mall.com/wp-content/uploads/2017/09/Muzaffarpur_Grand-Mall-300x200.png?x38496",
        location:"Mithanpura",
        city:"Muzaffarpur",
        type:"Mall",
    },
    {
        title:"P&M Mall",
        description:"P&M Mall in Muzaffarpur, located on Bela Road, is a major shopping and entertainment hub in the region. It features a hypermarket, departmental stores, a four-screen luxury multiplex (PJP Cinepolis), an entertainment zone, and diverse dining options in its food court and restaurants. The mall also provides amenities such as ample parking, and potentially a gym and hotel. Key retail outlets include Reliance Smart Point, Reliance Trends, and others offering fashion, accessories, and groceries. Overall, P&M Mall serves as a comprehensive destination for shopping, entertainment, and leisure for the residents and visitors of Muzaffarpur.",
        image:"https://scontent.fpat2-4.fna.fbcdn.net/v/t39.30808-6/481213831_1036817255131762_3998056071736809743_n.jpg?_nc_cat=101&ccb=1-7&_nc_sid=cc71e4&_nc_ohc=WGH6l0hEUBMQ7kNvwFseQoG&_nc_oc=Adl0aDczU_5CzEq19K5-a3yTiaAmL8crEo6tALEZRJLQKLNOZ4s_9Nx-gEidvkW7vpi5FuX4VcnJ25ktbxusMXkF&_nc_zt=23&_nc_ht=scontent.fpat2-4.fna&_nc_gid=BvgtjNeEYxFUhIXOFqk0ig&oh=00_AfIzB0vBf2xe7oAKQVsd1QZwObRLzNmBNgWfq7XvSm501A&oe=682404BC",
        location:"Swami Vivekanand Rd, opposite RK Ashram, Sherpur, Narayanpur Anant, Muzaffarpur, Bihar 842005",
        city:"Muzaffarpur",
        type:"Mall",
    },
    {
        title:"Icon Plaza",
        description:"Icon Plaza Mall in Muzaffarpur is a modern, state-of-the-art shopping mall and office complex that offers a comprehensive experience for visitors. It features a large retail area with anchor tenants like Big Bazaar and Pantaloons, a 300-seat food court, and a four-screen multiplex. The mall also boasts an arcade and offers amenities like parking, restrooms, and wheelchair accessibility. ",
        image:"https://www.mappls.com/place/0I9ENX_1710819473431_0.png",
        location:"Bhagwanpur,Muzaffarpur",
        city:"Muzaffarpur",
        type:"Mall",
    },
    {
        title:"Gayatri Mall",
        description:"Gayatri Mall in Muzaffarpur is a shopping mall with a diverse range of features. It offers various amenities, including arcade games, restrooms, and accessible facilities like a wheelchair accessible entrance and restroom. The mall also boasts onsite services and is known for its best grocery shopping and nice clothing.Furthermore, it's considered LGBTQ+ friendly.",
        image:"https://www.mappls.com/place/EC4DXZ_1657557190935_0.jpg",
        location:" New Zeromile, Muzaffarpur, NH-77, Muzaffarpur, Muzaffarpur, Bihar 842001",
        city:"Muzaffarpur",
        type:"Mall",
    },
    {
        title:"Citykart ",
        description:"Citykart Mall is a shopping mall that provides a comprehensive retail experience. It features a variety of stores catering to different needs, including fashion, electronics, and more. The mall is known for its vibrant atmosphere and friendly staff, making it a popular place for shopping and leisure. ",
        image:"https://dfupublications.com/images/2024/09/17/Citykart%20plans%20major%20expansion%20with%20launch%20of%20over%2025%20stores%20across%20India_large.jpg",
        location:"Om Tower, Near Mamaji Dry Cleaner, Aghoria Chowk, Amgola-842001.",
        city:"Muzaffarpur",
        type:"Mall",
    },
    {
        title:"Vishal Mega Mart",
        description:"Vishal Mega Mart is a hypermarket that caters to a wide range of customers, offering affordable and diverse shopping experiences. ",
        image:"https://content.jdmagicbox.com/comp/sitamarhi/d9/9999p6226.6226.220907181007.u2d9/catalogue/vishal-mega-mart-amghatta-sitamarhi-hypermarkets-lgh6l51ryy.jpg",
        location:"Amaze Shopping Mall, Imalichatti Road, Aghoria Bazaar, Muzaffarpur - 842002, near the Government Bus Stand.",
        city:"Muzaffarpur",
        type:"Mall",
    },
    {
        title:"V Mart",
        description:"t's a family fashion store offering a wide range of products under one roof, and is known for providing true value for money. The store aims to provide a great shopping experience with quality items at affordable prices. ",
        image:"https://files.yappe.in/place/full/v-mart-9846060.webp",
        location:"Ward No 27, Musahari, P.S. Kazi Mahmadpur",
        city:"Muzaffarpur",
        type:"Mall",
    },
    {
        title:"Reliance SMART Bazaar",
        description:"SMART Bazaar is a one-stop shopping destination for all your needs. It offers a wide range of Groceries, Homeware & Stylish Affordable Fashion. Choose from our range of Fruits & Vegetables, Staples, Dairy, Packaged Food, Home & Personal Care, largest range of Homeware Brands, and trendy apparel for Men's, Women’s & Kids",
        image:"https://i.ytimg.com/vi/rW-LYVPvQzA/sddefault.jpg",
        location:"The Grand Mall, Near Mddm College, Mithanpura, Muzaffarpur, Bihar.",
        city:"Muzaffarpur",
        type:"Mall",
    },
    {
        title:"Khadi Mall",
        description:"You can find a wide variety of Khadi, handicraft, and village industry products from Bihar at the Khadi Mall. ",
        image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTKxnhWx9epZhu4coPtT_rMuq15b5-xxx-rUVQzuec-NEqDRz4zdPia2qNS7Noo1jscw2o&usqp=CAU",
        location:"The Khadi Mall is situated at P&T Chowk, Gaushala Road, Muzaffarpur. ",
        city:"Muzaffarpur",
        type:"Mall",
    },
    {
        title:"DCC Mall ",
        description:"Dwarka City Center ",
        image:"https://upload.wikimedia.org/wikipedia/commons/thumb/f/f2/Dwarka_City_Center_Mall_Muzaffarpur.png/960px-Dwarka_City_Center_Mall_Muzaffarpur.png",
        location:"Majhaulia Rd, opposite Hotel The Heaven, Gobarsahi, Muzaffarpur, Gobrsahi urf Gobardhanpur, Bihar 842001",
        city:"Muzaffarpur",
        type:"Mall",
    },
    {
        title:"Kake Di Hatti - Muzaffarpur & Royal Banquet",
        description:"It is a popular North Indian restaurant chain known for its authentic dishes and especially large, signature Naans.",
        image:"https://lh3.googleusercontent.com/VuLrK34t3r7ONaDtqH1S-FeBiTs78fvV9qY2WszoiJevTY3Arl-YvxnmmfzDpNopKD_FWQO4R65o46C-wk7l6mYifH9brn4vSgnKdFw=w1200-rw",
        location:"1st floor, Park Central, in front of Jubba Sahni park, behind Bajaj Allianz, Mahammadpur Kazi, Mithanpura, Muzaffarpur, Bihar 842002",
        city:"Muzaffarpur",
        type:"Restaurant",
    },
    {
        title:"Moon night cafe & resto",
        description:"The restaurant's interior is elegantly designed to provide a cozy yet refined ambiance, with warm lighting and tasteful decor that make every meal feel special.",
        image:"https://content.jdmagicbox.com/v2/comp/muzaffarpur/y9/9999px621.x621.240830164241.i9y9/catalogue/rv3snuacnkftawi-7mymf1hpfn-250.jpg",
        location:"kalambagh chowk, Satsang Vihar, Muzaffarpur, Bihar 842002",
        city:"Muzaffarpur",
        type:"Restaurant",
    },
    {
        title:"The Cinnamon",
        description:"The Cinnamon is a well-known restaurant known for its Awadhi, Mexican, and fusion cuisine. ",
        image:"https://content.jdmagicbox.com/comp/muzaffarpur/z2/9999px621.x621.201007222849.p5z2/catalogue/the-cinnamon-aghoria-bazaar-muzaffarpur-restaurants-19wugzjvo7.jpg",
        location:"Pandey Complex, near Zenith Petrol Pump, Aghoria Bazar, Muzaffarpur, Bihar 842001",
        city:"Muzaffarpur",
        type:"Restaurant",
    },
    {
        title:"The Royal",
        description:"Serves vegan dishes · Good for kids birthday",
        image:"https://content.jdmagicbox.com/comp/muzaffarpur/q8/9999px621.x621.231123135909.u1q8/catalogue/lx29fsmdpngdrn9-qazro001da.jpg",
        location:"9PR+X2M, Shivalaya complex ground floor, Akharaghat Rd, near of Aditya visions zeromail, Muzaffarpur, Bihar 842002",
        city:"Muzaffarpur",
        type:"Restaurant",
    },
    {
        title:"Vyanjan",
        description:"This restaurant is beautiful atmosphere and beautiful Moon really OSM, And food is very 😋delicious and staff behavior was polite, entire restaurant was beautiful, Paneer tikka panner chilli and lachha pratha ummmmm very delicious I love that and lastly one word menu was affordable 😍",
        image:"https://files.yappe.in/place/small/vyanjan-4718333.webp",
        location:"Kalyani,Club Road, Mushari",
        city:"Muzaffarpur",
        type:"Restaurant",
    },
    {
        title:"Jackson Diner By Moti Mahal of India",
        description:"We offer 10 Franchise Models to choose from that will allow you to customize your restaurant to your personalized needs.",
        image:"https://lh3.googleusercontent.com/p/AF1QipNc8ICesR28yMlIRp6hyG23NXcB6rkEHm2i_44=w141-h235-n-k-no-nu",
        location:"Second Floor, Bansal Tower, Club Rd, in front of Hotel The Park, Mahammadpur Kazi, Mithanpura, Muzaffarpur",
        city:"Muzaffarpur",
        type:"Restaurant",
    },
    {
        title:"CAFE 23",
        description:"For those who appreciate quality food, a warm atmosphere, and attentive service, Cafe 23 in Amgola, Muzaffarpur is a must-visit destination.",
        image:"https://lh3.googleusercontent.com/gps-cs-s/AC9h4nrVqZR7FF6wF0-BMaL5bQd0gzKMMAwhZGNBLuvz3HK8wsgAMNS0Vv39koF886RBKLN-vvSAlvrwP6n26vFvkzV8Y1-Y6UvyQUDGnfru7-QZHfvn7W4l70g8bCrNur4PM_fYyh-mLg=s1360-w1360-h1020-rw",
        location:" Amgola Rd, opp. Orient club, near bharamakumari, Satsang Vihar, Muzaffarpur, Bihar 842001",
        city:"Muzaffarpur",
        type:"Restaurant",
    },
    {
        title:"The SR Grand",
        description:"The Sr Grand Restaurant Pub And Cafe is located in the heart of Patahi, a bustling neighborhood that's known for its lively atmosphere and vibrant nightlife.",
        image:"https://r1imghtlak.mmtcdn.com/9da398e9-2ea3-4117-9536-d093dfe3554d.jpg",
        location:"Patahi Rd, Muzaffarpur",
        city:"Muzaffarpur",
        type:"Restaurant",
    },
    {
        title:"Patna Foodies Club",
        description:"Patna Foodies Club is one of the best multi cuisine restaurants in town. We serve delicious and quality food to our customer.",
        image:"https://b.zmtcdn.com/data/pictures/5/21228175/841c22b1c78393afd66ac9a8d61ab2d6.jpeg",
        location:"DNC TOWER, Sahu Rd, Purani Bazar, Musahri, Muzaffarpur, Bihar 842001",
        city:"Muzaffarpur",
        type:"Restaurant",
    },
    {
        title:"JK Residency ",
        description:"K Residency in Muzaffarpur is a 3-star restaurant offering a range of amenities and services.",
        image:"https://images.trvl-media.com/lodging/106000000/105450000/105448700/105448609/03767cb9.jpg?impolicy=resizecrop&rw=575&rh=575&ra=fill",
        location:"Maripur Main Rd, Tilak Nagar, Muzaffarpur",
        city:"Muzaffarpur",
        type:"Restaurant",
    },
    {
        title:"The Table cafe",
        description:"Has all you can eat · Has outdoor seating · Good for kids birthday",
        image:"https://lh3.googleusercontent.com/p/AF1QipNcR9s5DOdE5rD8aOPbUnfQZ3uJnusV1fTkOUvr=s1360-w1360-h1020-rw",
        location:" NH-28, near Holi mission school, Sherpur, Muzaffarpur",
        city:"Muzaffarpur",
        type:"Restaurant",
    },
    {
        title:"The BBQ(BAR-BE-QUE)",
        description:"The BBQ in Muzaffarpur stands out for its live grill experience, offering a variety of grilled specialties, including live grilling of starters and a diverse menu catering to both vegetarian and non-vegetarian preferences. Restaurants like The BBQ and Barbeque Nation also offer all-you-can-eat buffets with live grilling, a key feature of the popular casual dining experience. ",
        image:"https://content.jdmagicbox.com/comp/muzaffarpur/y2/9999px621.x621.230301184129.z1y2/catalogue/the-bbq-ramna-muzaffarpur-restaurants-63ol898mn6-250.jpg",
        location:"EB Star Market, Club Rd, near Aditya Vision, Mithanpura, Muzaffarpur",
        city:"Muzaffarpur",
        type:"Restaurant",
    },
    {
        title:"Kesariya Food Court",
        description:"is a popular restaurant and food court offering a variety of cuisines, including Chinese, North Indian, street food, and fast food.",
        image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTBBJ0KUYXDgqq1yzn7FNDgQ-v9B1VWPnAMzQ&s",
        location:"kalambagh Chowk, Satsang Vihar, Muzaffarpur",
        city:"Muzaffarpur",
        type:"Restaurant",
    },
    {
        title:"THE DHABA-YARA DI RASOI",
        description:"Soul satisfying taste. Very good and peaceful ambience. Drinks were also good. The most important thing is that everything is fresh. I have ordered momo which was really very nice and butter naan and paneer kalezi, the taste of paneer kalezi was like superb. It’s also budget friendly and very nice place to go with friends and family",
        image:"https://lh3.googleusercontent.com/gps-cs-s/AC9h4npQ1GJWjV5HSJ9YnvgctY1zbi5eWzd8BznHd-eVy_zgsq6Yk6qlOm7IufhpHkGN0uzx5F8gI-hNYnIABH_BxIDTyydkdSPREI_LapFkU2iDL_hryICbtWnMqZkbNI14BrU8yhOePA=s1360-w1360-h1020-rw",
        location:"BALIGAR GARDEN, CLUB ROAD INFRONT OF GRAND MALL",
        city:"Muzaffarpur",
        type:"Restaurant",
    },
    {
        title:"Chatkara Cafe",
        description:"For those who appreciate quality food, a warm atmosphere, and attentive service",
        image:"https://lh3.googleusercontent.com/p/AF1QipPz4mPf1titjNdYHHnyeKOaSx45GrUqCFmtZmfC=s1360-w1360-h1020-rw",
        location:"near V-mart, Mahammadpur Kazi, Aghoria Bazar, Saadpur, Muzaffarpur, Bihar 842002",
        city:"Muzaffarpur",
        type:"Restaurant",
    },
    {
        title:"London Bridge Rooftop",
        description:" It is a popular spot known for its upscale ambiance, rooftop setting, and diverse menu.",
        image:"https://i0.wp.com/muzaffarpurcity.com/wp-content/uploads/2022/06/London-Bridge-Roof-Top-restaurant-Muzaffarpur-2.jpg?resize=640%2C360&ssl=1",
        location:"Mithanpura, Muzaffarpur ",
        city:"Muzaffarpur",
        type:"Restaurant",
    },
    {
        title:"Neighborhood Restaurant & Banquet Hall",
        description:"Best restaurant with best taste",
        image:"https://content.jdmagicbox.com/comp/muzaffarpur/z2/9999px621.x621.201007222849.p5z2/catalogue/the-cinnamon-aghoria-bazaar-muzaffarpur-restaurants-1vmqgqvxzp-250.jpg",
        location:"Infront of L.N. Mishra Collage, Neighborhood Restaurant & Banquet Hall, Bhagwanpur Golamber, IG Colony Rd, Muzaffarpur, Bihar 842001",
        city:"Muzaffarpur",
        type:"Restaurant",
    },
    {
        title:"Bharat Jalpan",
        description:"It's a popular spot for casual dining, offering a cozy and refined ambiance. Jalpan is also known for its fast food options like rolls and chicken chili, and some patrons appreciate its affordability. ",
        image:"https://files.yappe.in/place/full/shri-bharat-jalpan-3105457.webp",
        location:"U. B Tower, Saraiya Ganj, Muzaffarpur Locality, Muzaffarpur City.",
        city:"Muzaffarpur",
        type:"Restaurant",
    },
    {
        title:"McDonald's",
        description:"It's recognized as a popular fast-food restaurant known for quality ingredients and service. ",
        image:"https://lh3.googleusercontent.com/gps-cs-s/AC9h4npgBmodFOPxdHAa1lk5obRV-HPEyKK9N6fEGdhHzkuCk14rQzdt9xTrNq3lmy46rhLyh_-ilgSRTcL6ea50DF767mTBx1JGxmTdlgJgQ2CdZMCgu58vlUMQ1VyMWVJrF8qcSVI=s1360-w1360-h1020-rw",
        location:"G06 Ground, Dwarka City Center Mall, Shop No- G01 to, NH-28, Majhaulia Rd, opposite MPS Science College, DCC, Muzaffarpur, Bihar 842002",
        city:"Muzaffarpur",
        type:"Restaurant",
    },
    {
        title:"The Landmark Hotel",
        description:"A modern hotel offering comfortable accommodations and excellent service.",
        image:"https://lh3.googleusercontent.com/gps-cs-s/AC9h4npC1oTgBGYZq9ye9AHSf0w6zoCstrecD7y3lgPpE2SMQ8if_dLSbloEyBiNhH8PoAG8tjbidfv9zjWIs23VmBl4oNOMkeae5_Ek8qF3gXGcUCo8ftdCQUGtb4qM91ljLDuDVEqt=s1360-w1360-h1020-rw",
        location:"Maripur Chowk, above Reliance Digital, Maripur, Muzaffarpur.(Near the city center)",
        city:"Muzaffarpur",
        type:"Hotel",
    },
    {
        title:"Hotel Central Park",
        description:" A cozy hotel with a restaurant and conference facilities.",
        image:"https://lh3.googleusercontent.com/gps-cs-s/AC9h4nrc95YVjwGG-sKcvH4W8PKFk4gSDcK7D_TVmHT2fco-N3jqyNeK7TZuS-nG41jPQ4u1485PjsEXy8o7dxbnwgvvox866zFXg9XHTFh0gSaLomEZdZ8t7agsTSl1odY9PrYyoBx3=s1360-w1360-h1020-rw",
        location:"Amgola Rd, Mahammadpur Kazi, Aghoria Bazar, Chowk, Muzaffarpur.",
        city:"Muzaffarpur",
        type:"Hotel",
    },
    {
        title:"Hotel Embassy International",
        description:"Known for its hospitality and well-furnished rooms.",
        image:"https://lh3.googleusercontent.com/p/AF1QipP5ey7lWTNSTyhGjBbwj_ilN0KjH9BDUIGYxb8_=s1360-w1360-h1020-rw",
        location:" ZILA PARISHAD MARKET, STATION ROAD, MUZAFFARPUR",
        city:"Muzaffarpur",
        type:"Hotel",
    },
    {
        title:"The Green Heritage Resort & Banquet",
        description:"Luxury hotel providing serene ambiance, exquisite swimming pool, elegant rooms, and impeccable service.",
        image:"https://lh3.googleusercontent.com/p/AF1QipM4sBtCKl-LKP4iu2gRJ8E_L4jnsOKnMWtPKZQg=s1360-w1360-h1020-rw",
        location:"Gobarsahi area.",
        city:"Muzaffarpur",
        type:"Hotel",
    },
    {
        title:"Ratna Hotel & Banquet",
        description:"A popular choice for events and family gatherings",
        image:"https://cf.bstatic.com/xdata/images/hotel/max1024x768/462372152.jpg?k=dd7950e93ec673464bd3857e276bdb15dad353e5c1c76863da82ecc8df4b90c6&o=&hp=1",
        location:" Akharaghat Rd, near FCI Godown, Akharghat, Muzaffarpur, Bihar 842001",
        city:"Muzaffarpur",
        type:"Hotel",
    },
    {
        title:"The Emerald Hotel",
        description:"Features modern amenities and a rooftop restaurant.",
        image:"https://lh3.googleusercontent.com/gps-cs-s/AC9h4noMf6MnmCUQnGpvaU0S-ang1EIdaza7E_7xTgLlgKjmjBUwQMskWfRU_A-9yhY-GN2gFHcaVJDXI-F87_MyKtBT6oW5daewUBP7LW9dFFd5Np589mnHXSD3SZSYebZbFOkIIELlgQ=s1360-w1360-h1020-rw",
        location:"Lenin chowk, Majhaulia Rd, Musahri(Central Muzaffarpur).",
        city:"Muzaffarpur",
        type:"Hotel",
    },
    {
        title:"Hotel JK Residency",
        description:"Offers comfortable rooms and a business center.",
        image:"https://images.trvl-media.com/lodging/106000000/105450000/105448700/105448609/03767cb9.jpg?impolicy=resizecrop&rw=575&rh=575&ra=fill",
        location:" Maripur Main Rd, Tilak Nagar, Muzaffarpur, Bihar 842001.",
        city:"Muzaffarpur",
        type:"Hotel",
    },
    {
        title:"Blue Diamond Resort & Hotel",
        description:"A resort-style hotel with recreational facilities.",
        image:"https://cf.bstatic.com/xdata/images/hotel/max1024x768/280651619.jpg?k=bf88bfa84e8058e31b8eea7613c7f2f4d1f99f85be975ce9f3a1369eb2bf6a31&o=&hp=1",
        location:"NH- 57, Garha, Darbhanga Road, Muzaffarpur(On the outskirts of the city).",
        city:"Muzaffarpur",
        type:"Hotel",
    },
    {
        title:"Motel New Milan",
        description:"Budget-friendly hotel with essential amenities.",
        image:"https://r1imghtlak.mmtcdn.com/6dbfc03ed6b511ebb24b0242ac110007.png",
        location:" 4956+FP, Chowk N.H.-28, Gobarsahi, Muzaffarpur, Gobrahi urf Gobardhanpur, Bihar 842001.",
        city:"Muzaffarpur",
        type:"Hotel",
    },
    {
        title:"Hotel Atithi",
        description:" Known for its warm hospitality and clean rooms",
        image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTnt7zynAGcJTnzeJPNSB0QN5GzQaZ845jJ0w&s",
        location:"opposite Sahid Parmod Petrol Pump, Ramdayalu Nagar, Muzaffarpur, Bihar 842002.",
        city:"Muzaffarpur",
        type:"Hotel",
    },
    {
        title:"Hotel Royal Phular",
        description:"Offers luxury accommodations with a touch of elegance.",
        image:"https://media-cdn.tripadvisor.com/media/photo-p/28/b0/4f/42/property-view.jpg",
        location:"Maripur Chowk, Maripur Main Rd, Muzaffarpur(Near the main market).",
        city:"Muzaffarpur",
        type:"Hotel",
    },
    {
        title:"Hotel Simna International",
        description:"A budget hotel with basic amenities and good service.",
        image:"https://r1imghtlak.mmtcdn.com/429fab0f-0f07-4cc0-994a-1e7603ece66e.jpeg",
        location:"Power House, Chowk, Maripur Main Rd, Muzaffarpur, Bihar 842001.",
        city:"Muzaffarpur",
        type:"Hotel",
    },
    {
        title:"Hotel Urmila International",
        description:"Hotel Urmila International in Muzaffarpur is known for its comfortable accommodations, good location near the railway station, and friendly service. The hotel offers various room types, including Deluxe Rooms, Executive Suites, and Family Suites, catering to different traveler needs. It provides amenities like WiFi, attached bathrooms, and air conditioning in all rooms. Additionally, the hotel offers a 24/7 concierge service, a fitness center, and spa facilities.",
        image:"https://content3.jdmagicbox.com/comp/muzaffarpur/q1/9999px621.x621.130411163602.h4q1/catalogue/hotel-urmila-international-station-road-muzaffarpur-hotels-a5by6chgg8.jpg",
        location:"Maripur Main Rd, near overbridge, Tilak Nagar, Muzaffarpur, Bihar 842001.",
        city:"Muzaffarpur",
        type:"Hotel",
    },
    {
        title:"The Jamun Tree",
        description:" It's described as a boutique, luxurious property with modern amenities, including well-equipped conference halls and banquet spaces, ideal for events and celebrations. The hotel also boasts a multi-cuisine restaurant and a large lawn/garden for relaxation.",
        image:"https://cf.bstatic.com/xdata/images/hotel/max1024x768/488795975.jpg?k=b806b0ef5982dc229c2176645f586f0a8539a3751654b1a9f889223a41236118&o=&hp=1",
        location:"Situated on National Highway 28, near Muzaffarpur Town.",
        city:"Muzaffarpur",
        type:"Hotel",
    },
    {
        title:"Mehma Nawazi",
        description:"is a multi-cuisine restaurant known for its Mughlai, Chinese, and Indian dishes. It offers a cozy ambiance and a variety of food options, including breakfast combos, parathas, and biryanis.",
        image:"https://content.jdmagicbox.com/comp/muzaffarpur/h5/9999px621.x621.240420151612.x8h5/catalogue/c8b2f0jwvmb3k5j-7yaxq7tswr.jpg",
        location:"Hotel Pratap INN, C/O, opp. Aadarsh Nagar, near Bairiya Bus Stand, Muzaffarpur, Paigamber Pur Kolhua.",
        city:"Muzaffarpur",
        type:"Hotel",
    },
    {
        title:"Hotel Shivam",
        description:"Budget accommodation with essential services.",
        image:"https://content3.jdmagicbox.com/comp/def_content/hotels-seating/dfa3s0kcpb-hotels-seating-2-c8k8v.jpg",
        location:"B.C. Plaza, Motijheel Rd, opp. Jaandar Shoes & Sanjay Opticals, Muzaffarpur, Bihar 842001.",
        city:"Muzaffarpur",
        type:"Hotel"
    },
    {
        title:"The Mantis",
        description:"The Mantis in Muzaffarpur is a luxurious hotel known for its high-end amenities, elegant design, and focus on customer satisfaction. It's located in the heart of Muzaffarpur and offers a unique blend of comfort and luxury for guests..",
        image:"https://r1imghtlak.mmtcdn.com/87d7418e-ec7d-49dc-a1c3-6ee36fd45692.jpeg",
        location:"2nd Floor, S. K. Foods & Beverages, Chhata Chowk, Pokhraira, Muzaffarpur.",
        city:"Muzaffarpur",
        type:"Hotel",
    },
    {
        title:"Hotel New Raj",
        description:"A budget-friendly option with basic amenities.",
        image:"https://r1imghtlak.mmtcdn.com/017e88f8b12211edbead0a58a9feac02.jpeg",
        location:" Near the railway station.",
        city:"Muzaffarpur",
        type:"Hotel",
    },
    {
        title:"Hotel Shree Ganesh",
        description:" It is a multi-faceted establishment that includes a Vivah Bhawan (wedding hall) and Guest House. It's located in the Brahampura area, near Bariya Bus Stand, and is known for its comfort, elegance, and hospitality, .",
        image:"https://content.jdmagicbox.com/comp/muzaffarpur/c3/9999px621.x621.170925190141.w6c3/catalogue/shri-ganesh-vivah-bhawan-and-guest-house-brahampura-muzaffarpur-guest-house-xf1zz5yy67.jpg",
        location:"Brahampura, near the Bank of Baroda and Bariya Bus Stand.",
        city:"Muzaffarpur",
        type:"Hotel",
    },
    {
        title:"Hotel Swarg",
        description:"A simple hotel with a friendly atmosphere.",
        image:"https://r1imghtlak.ibcdn.com/1d44ebb6e57e11eb9cab0242ac110004.png?&output-quality=75&downsize=350:238&crop=350:238;0,34&output-format=jpg",
        location:"National Highway 28, Bhagwanpur, Shrirampuri, Muzaffarpur, Bihar 842001.",
        city:"Muzaffarpur",
        type:"Hotel",
    },
    
];
module.exports = {data: alldata};